# .streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyBfhVSuZj8t6uzboQ8WHu-DnxrB6TbIkbY"
CLIENT_ID = "279518903393-2j7i36bm86vues8rmrhetaje4htcf9t7.apps.googleusercontent.com"
CLIENT_SECRET = "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"
GOOGLE_APPLICATION_CREDENTIALS = "dietvision-service-account.json"
PROJECT_ID = "279518903393"
ENDPOINT_ID = "8599983028766244864"
REGION = "us-central1"
REDIRECT_URI_LOCAL = "http://localhost:8501"
REDIRECT_URI_DEPLOYED = "https://diet-vision-smartplaters.streamlit.app"